name: express
description: Mobile Application that handles the shipping operations of Bra7tak E-Commerce Website

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
